#!/bin/bash
## information bar

## colors and  fonts
BG=$(cat ${CD} | grep -i background | tail -c 8)
FG=$(cat ${CD} | grep -i foreground | tail -c 8)

BLACK=$(cat ${CD} | grep -i color8 | tail -c 8)
RED=$(cat ${CD} | grep -i color9 | tail -c 8)
GREEN=$(cat ${CD} | grep -i color10 | tail -c 8)
YELLOW=$(cat ${CD} | grep -i color11 | tail -c 8)
BLUE=$(cat ${CD} | grep -i color12 | tail -c 8)
MAGENTA=$(cat ${CD} | grep -i color13 | tail -c 8)
CYAN=$(cat ${CD} | grep -i color14 | tail -c 8)
WHITE=$(cat ${CD} | grep -i color15 | tail -c 8)
## glyphs
  glymem="MEM"
  glycpu="CPU"
  glytemp="TMP"
  glypkg="KG"
  glyclock="H"
  glycal="AL"
## extras
  SEP=" "
  SEP2="  "
  SEP3="   "
  SEP4="    "
  SEP6="       "
  SEP8="        "
## information section
status() {
    cpuld() {
        cpuload=$(cpu)
        echo %{F$CYAN}$glycpu$SEP$cpuload%{F-}
    }

    memory() {
        mem=$(free -m | awk 'NR==2 {print $3}')
        mem+="MB"
        echo %{F$RED}$glymem$SEP$mem%{F-}
    }

    overclock() {
        temp=$((`sensors | grep "Physical id 0" | cut -d'+' -f2 | head -c2`))
        echo %{F$YELLOW}$glytemp$SEP$temp°%{F-}
    }

	pkgupdates() {
		pkgu=$(cat /tmp/current_updates.output)
		echo %{F$BLUE}$glypkg$SEP$pkgu%{F-}
	}

    vol() {
        vlm=$(pamixer --get-volume)
        glyvol=""
        echo %{F$MAGENTA}$glyvol$SEP$vlm$SEP%{F-}
    }

	clockdate() {
	    clockd=%{F$GREEN}$glycal$(date +%{F$GREEN}' %d   %b')%{F-}
        clockt=%{F$CYAN}$glyclock$(date +' %R')%{F-}
        echo $clockd
    }

    clocktime() {
        clockt=%{F$CYAN}$glyclock$(date +' %R')%{F-}
        echo $clockt
    }
    echo "%{c}$SEP4$(cpuld)$SEP4$(memory)$SEP4$(overclock)$SEP4$(pkgupdates)$SEP4$(vol)$SEP3$(clockdate)$SEP4$(clocktime)$SEP4"
}

pamixer --get-volume # resolves no text at start bug
while true
do
  echo "$(status)"
  sleep 2
  done | lemonbar -g $notifybar_g -d -f "terminus12-8" -f "FontAwesome:size=8" -B $BG -F $WHITE
